export default {
   products: [
      {
         _id: '111111111111111111111111',
         name: 'Character top',
         category: 'Shirts',
         image: 'images/IMG-20200728-WA0049.jpg',
         price: 3000,
         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quibusdam maxime aperiam laborum voluptates unde illum rerum deleniti, dicta, consequatur minus nostrum ratione quia debitis eum beatae hic ad fugit.',
         rating: 4.5,
         numReviews: 10,
         countInStock: 6,
      },
      {
         _id: '222222222222222222222222',
         name: 'Hoodie',
         category: 'Shirts',
         price: 5000,
         description: 'then the number',
         image: 'images/IMG-20200728-WA0055.jpg',
         rating: 4.5,
         numReviews: 10,
         countInStock: 6,
      },
      {
         _id: '333333333333333333333333',
         name: 'Hoodie',
         category: 'Shirts',
         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quibusdam maxime aperiam laborum voluptates unde illum rerum deleniti, dicta, consequatur minus nostrum ratione quia debitis eum beatae hic ad fugit.',
         image: 'images/IMG-20200728-WA0058.jpg',
         price: 7000,
         rating: 4.5,
         numReviews: 10,
         countInStock: 6,
      },
      {
         _id: '444444444444444444444444',
         name: 'Hoodie',
         category: 'Shirts',
         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quibusdam maxime aperiam laborum voluptates unde illum rerum deleniti, dicta, consequatur minus nostrum ratione quia debitis eum beatae hic ad fugit.',
         image: 'images/IMG-20200728-WA0061.jpg',
         price: 3000,
         rating: 4.5,
         numReviews: 10,
         countInStock: 6,
      },
      {
         _id: '555555555555555555555555',
         name: 'Hoodie and top',
         category: 'Shirts',
         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quibusdam maxime aperiam laborum voluptates unde illum rerum deleniti, dicta, consequatur minus nostrum ratione quia debitis eum beatae hic ad fugit.',
         image: 'images/IMG-20200728-WA0062.jpg',
         price: 3500,
         rating: 4.5,
         numReviews: 10,
         countInStock: 0,
      },
      {
         _id: '666666666666666666666666',
         name: 'Shirt and Trouser',
         category: 'Shirts',
         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Est quibusdam maxime aperiam laborum voluptates unde illum rerum deleniti, dicta, consequatur minus nostrum ratione quia debitis eum beatae hic ad fugit.',
         image: 'images/IMG-20200728-WA0068.jpg',
         price: 3700,
         rating: 4.5,
         numReviews: 10,
         countInStock: 6,
      },
   ],
}